---
- hosts: web_servers
  become: true
  tasks:
    - name: Update repo and Install nginx
      apt:
        name: "nginx"
        state: present
        update_cache: yes

    - name: Create folder for website
      file: 
        path: "/var/www/{ website_name }"
        state: directory

    - name: Delete sites-enable and sites-available files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/nginx/sites-enabled/default"
        - "/etc/nginx/sites-available/default"
